import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const dyslexiaFont = localFont({
  src: [
    {
      path: "../../public/fonts/OpenDyslexic-Regular.woff2", // Use the correct path relative to /public
      weight: "normal", // optional, specify the weight if applicable
      style: "normal", // optional, specify the style
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dyslexiaFont.className} antialiased bg-[#FFF7EF] text-[#1D0066]`}
      >
        {children}
      </body>
    </html>
  );
}
